/* USER INFORMATION */
export const GET_USER_PROPERTIES = 'GET_USER_PROPERTIES';
export const GET_USER_PROPERTIES_SUCCESS = 'GET_USER_PROPERTIES_SUCCESS';
export const GET_USER_PROPERTIES_FAIL = 'GET_USER_PROPERTIES_FAIL';

/* USER PROFILE PICTURE */
export const GET_USER_IMAGE = 'GET_USER_IMAGE';
export const GET_USER_IMAGE_SUCCESS = 'GET_USER_IMAGE_SUCCESS';
export const GET_USER_IMAGE_FAIL = 'GET_USER_IMAGE_FAIL';
