export const GET_TERMINAL = "GET_TERMINAL"
export const GET_TERMINAL_SUCCESS = "GET_TERMINAL_SUCCESS"
export const GET_TERMINAL_FAIL = "GET_TERMINAL_FAIL"

// download
export const GET_DOWNLOAD_TERMINAL = "GET_DOWNLOAD_TERMINAL"
export const GET_DOWNLOAD_TERMINAL_SUCCESS = "GET_DOWNLOAD_TERMINAL_SUCCESS"
export const GET_DOWNLOAD_TERMINAL_FAIL = "GET_DOWNLOAD_TERMINAL_FAIL"

/* AUDIT LOG */
export const GET_TERMINAL_AUDITLOG = "TERMINAL_AUDITLOG"
export const GET_TERMINAL_AUDITLOG_SUCCESS = "GET_TERMINAL_AUDITLOG_SUCCESS"
export const GET_TERMINAL_AUDITLOG_FAIL = "GET_TERMINAL_AUDITLOG_FAIL"

/* TABLE INFORMATION */
export const GET_TERMINAL_TABLE_INFORMATION = "GET_TERMINAL_TABLE_INFORMATION"
export const GET_TERMINAL_TABLE_INFORMATION_SUCCESS = "GET_TERMINAL_TABLE_INFORMATION_SUCCESS"
export const GET_TERMINAL_TABLE_INFORMATION_FAIL = "GET_TERMINAL_TABLE_INFORMATION_FAIL"

export const UPDATE_TERMINAL_TABLE_INFORMATION = "UPDATE_TERMINAL_TABLE_INFORMATION"
export const UPDATE_TERMINAL_TABLE_INFORMATION_SUCCESS =
  "UPDATE_TERMINAL_TABLE_INFORMATION_SUCCESS"
export const UPDATE_TERMINAL_TABLE_INFORMATION_FAIL = "UPDATE_TERMINAL_TABLE_INFORMATION_FAIL"

export const RESET_CURRENT_TERMINAL_DETAIL = "RESET_CURRENT_TERMINAL_DETAIL"

/* FILTER */
export const GET_TERMINAL_FILTER = "TERMINAL_FILTER"
export const GET_TERMINAL_FILTER_SUCCESS = "GET_TERMINAL_FILTER_SUCCESS"
export const GET_TERMINAL_FILTER_FAIL = "GET_TERMINAL_FILTER_FAIL"
