export const GET_COMMERCIAL_CUSTOMER = "GET_COMMERCIAL_CUSTOMER"
export const GET_COMMERCIAL_CUSTOMER_SUCCESS = "GET_COMMERCIAL_CUSTOMER_SUCCESS"
export const GET_COMMERCIAL_CUSTOMER_FAIL = "GET_COMMERCIAL_CUSTOMER_FAIL"

// DOWNOAD EXCEL
export const GET_DOWNLOAD_COMMERCIAL_CUSTOMER = "GET_DOWNLOAD_COMMERCIAL_CUSTOMER"
export const GET_DOWNLOAD_COMMERCIAL_CUSTOMER_SUCCESS = "GET_DOWNLOAD_COMMERCIAL_CUSTOMER_SUCCESS"
export const GET_DOWNLOAD_COMMERCIAL_CUSTOMER_FAIL = "GET_DOWNLOAD_COMMERCIAL_CUSTOMER_FAIL"

/* AUDIT LOG */
export const GET_COMMERCIAL_AUDITLOG = "COMMERCIAL_AUDITLOG"
export const GET_COMMERCIAL_AUDITLOG_SUCCESS = "GET_COMMERCIAL_AUDITLOG_SUCCESS"
export const GET_COMMERCIAL_AUDITLOG_FAIL = "GET_COMMERCIAL_AUDITLOG_FAIL"

export const GET_COMMERCIAL_FILTER = "COMMERCIAL_FILTER"
export const GET_COMMERCIAL_FILTER_SUCCESS = "GET_COMMERCIAL_FILTER_SUCCESS"
export const GET_COMMERCIAL_FILTER_FAIL = "GET_COMMERCIAL_FILTER_FAIL"

/* TABLE INFORMATION */
export const GET_COMMERCIAL_TABLE_INFORMATION = "GET_COMMERCIAL_TABLE_INFORMATION"
export const GET_COMMERCIAL_TABLE_INFORMATION_SUCCESS = "GET_COMMERCIAL_TABLE_INFORMATION_SUCCESS"
export const GET_COMMERCIAL_TABLE_INFORMATION_FAIL = "GET_COMMERCIAL_TABLE_INFORMATION_FAIL"

export const UPDATE_COMMERCIAL_TABLE_INFORMATION = "UPDATE_COMMERCIAL_TABLE_INFORMATION"
export const UPDATE_COMMERCIAL_TABLE_INFORMATION_SUCCESS = "UPDATE_COMMERCIAL_TABLE_INFORMATION_SUCCESS"
export const UPDATE_COMMERCIAL_TABLE_INFORMATION_FAIL = "UPDATE_COMMERCIAL_TABLE_INFORMATION_FAIL"
export const RESET_COMMERCIAL_TABLE_INFORMATION = "RESET_COMMERCIAL_TABLE_INFORMATION"