export const GET_COMMERCIAL_CUSTOMER = "GET_COMMERCIAL_CUSTOMER"
export const GET_COMMERCIAL_CUSTOMER_SUCCESS = "GET_COMMERCIAL_CUSTOMER_SUCCESS"
export const GET_COMMERCIAL_CUSTOMER_FAIL = "GET_COMMERCIAL_CUSTOMER_FAIL"

/* AUDIT LOG */
export const GET_COMMERCIAL_AUDITLOG = "COMMERCIAL_AUDITLOG"
export const GET_COMMERCIAL_AUDITLOG_SUCCESS = "GET_COMMERCIAL_AUDITLOG_SUCCESS"
export const GET_COMMERCIAL_AUDITLOG_FAIL = "GET_COMMERCIAL_AUDITLOG_FAIL"

export const GET_COMMERCIAL_FILTER = "COMMERCIAL_FILTER"
export const GET_COMMERCIAL_FILTER_SUCCESS = "GET_COMMERCIAL_FILTER_SUCCESS"
export const GET_COMMERCIAL_FILTER_FAIL = "GET_COMMERCIAL_FILTER_FAIL"