export const GET_RETAIL_CUSTOMER = "GET_RETAIL_CUSTOMER"
export const GET_RETAIL_CUSTOMER_SUCCESS = "GET_RETAIL_CUSTOMER_SUCCESS"
export const GET_RETAIL_CUSTOMER_FAIL = "GET_RETAIL_CUSTOMER_FAIL"

/* AUDIT LOG */
export const GET_COMMERCIAL_AUDITLOG = "RETAIL_AUDITLOG"
export const GET_COMMERCIAL_AUDITLOG_SUCCESS = "GET_RETAIL_AUDITLOG_SUCCESS"
export const GET_COMMERCIAL_AUDITLOG_FAIL = "GET_RETAIL_AUDITLOG_FAIL"
