export const GET_SLA_ITEMS = "GET_SLA_ITEMS"
export const GET_SLA_ITEMS_SUCCESS = "GET_SLA_ITEMS_SUCCESS"
export const GET_SLA_ITEMS_FAIL = "GET_SLA_ITEMS_FAIL"

/* AUDIT LOG */
export const GET_SLA_AUDITLOG = "GET_SLA_AUDITLOG"
export const GET_SLA_AUDITLOG_SUCCESS = "GET_SLA_AUDITLOG_SUCCESS"
export const GET_SLA_AUDITLOG_FAIL = "GET_SLA_AUDITLOG_FAIL"


export const UPDATE_SLA_DETAIL = "UPDATE_SLA_DETAIL"
export const UPDATE_SLA_DETAIL_SUCCESS = "UPDATE_SLA_DETAIL_SUCCESS"
export const UPDATE_SLA_DETAIL_FAIL = "UPDATE_SLA_DETAIL_FAIL"

// sla-modal-detail
export const DELETE_SLA_DETAIL = "DELETE_SLA_DETAIL"
export const DELETE_SLA_DETAIL_SUCCESS = "DELETE_SLA_DETAIL_SUCCESS"
export const DELETE_SLA_DETAIL_FAIL = "DELETE_SLA_DETAIL_FAIL"
export const UPDATE_SLA_SECTION_NOTE = "UPDATE_SLA_SECTION_NOTE"
export const UPDATE_SLA_SECTION_NOTE_SUCCESS = "UPDATE_SLA_SECTION_NOTE_SUCCESS"
export const UPDATE_SLA_SECTION_NOTE_FAIL = "UPDATE_SLA_SECTION_NOTE_FAIL"
