export const GET_ROAD_TANKER = "GET_ROAD_TANKER"
export const GET_ROAD_TANKER_SUCCESS = "GET_ROAD_TANKER_SUCCESS"
export const GET_ROAD_TANKER_FAIL = "GET_ROAD_TANKER_FAIL"

/* DOWNLOAD */
export const GET_DOWNLOAD_ROAD_TANKER = "GET_DOWNLOAD_ROAD_TANKER"
export const GET_DOWNLOAD_ROAD_TANKER_SUCCESS =
  "GET_DOWNLOAD_ROAD_TANKER_SUCCESS"
export const GET_DOWNLOAD_ROAD_TANKER_FAIL = "GET_DOWNLOAD_ROAD_TANKER_FAIL"

/* AUDIT LOG */
export const GET_ROADTANKER_AUDITLOG = "ROADTANKER_AUDITLOG"
export const GET_ROADTANKER_AUDITLOG_SUCCESS = "GET_ROADTANKER_AUDITLOG_SUCCESS"
export const GET_ROADTANKER_AUDITLOG_FAIL = "GET_ROADTANKER_AUDITLOG_FAIL"

/* FILTER */
export const GET_ROADTANKER_FILTER = "ROADTANKER_FILTER"
export const GET_ROADTANKER_FILTER_SUCCESS = "GET_ROADTANKER_FILTER_SUCCESS"
export const GET_ROADTANKER_FILTER_FAIL = "GET_ROADTANKER_FILTER_FAIL"

/* DETAIL */
export const GET_ROAD_TANKER_DETAIL = "GET_ROAD_TANKER_DETAIL"
export const GET_ROAD_TANKER_DETAIL_SUCCESS = "GET_ROAD_TANKER_DETAIL_SUCCESS"
export const GET_ROAD_TANKER_DETAIL_FAIL = "GET_ROAD_TANKER_DETAIL_FAIL"
export const RESET_CURRENT_ROAD_TANKER_DATA = "RESET_CURRENT_ROAD_TANKER_DATA"

export const UPDATE_ROAD_TANKER_DETAIL = "UPDATE_ROAD_TANKER_DETAIL"
export const UPDATE_ROAD_TANKER_DETAIL_SUCCESS =
  "UPDATE_ROAD_TANKER_DETAIL_SUCCESS"
export const UPDATE_ROAD_TANKER_DETAIL_FAIL = "UPDATE_ROAD_TANKER_DETAIL_FAIL"
