export const GET_ROAD_TANKER = "GET_ROAD_TANKER"
export const GET_ROAD_TANKER_SUCCESS = "GET_ROAD_TANKER_SUCCESS"
export const GET_ROAD_TANKER_FAIL = "GET_ROAD_TANKER_FAIL"

/* DOWNLOAD */
export const GET_DOWNLOAD_ROAD_TANKER = "GET_DOWNLOAD_ROAD_TANKER"
export const GET_DOWNLOAD_ROAD_TANKER_SUCCESS = "GET_DOWNLOAD_ROAD_TANKER_SUCCESS"
export const GET_DOWNLOAD_ROAD_TANKER_FAIL = "GET_DOWNLOAD_ROAD_TANKER_FAIL"

/* AUDIT LOG */
export const GET_ROADTANKER_AUDITLOG = "ROADTANKER_AUDITLOG"
export const GET_ROADTANKER_AUDITLOG_SUCCESS = "GET_ROADTANKER_AUDITLOG_SUCCESS"
export const GET_ROADTANKER_AUDITLOG_FAIL = "GET_ROADTANKER_AUDITLOG_FAIL"

/* TABLE INFORMATION */
export const GET_TABLE_INFORMATION = "TABLE_INFORMATION"
export const GET_TABLE_INFORMATION_SUCCESS = "GET_TABLE_INFORMATION_SUCCESS"
export const GET_TABLE_INFORMATION_FAIL = "GET_TABLE_INFORMATION_FAIL"

export const UPDATE_TABLE_INFORMATION = "UPDATE_TABLE_INFORMATION"
export const UPDATE_TABLE_INFORMATION_SUCCESS =
  "UPDATE_TABLE_INFORMATION_SUCCESS"
export const UPDATE_TABLE_INFORMATION_FAIL = "UPDATE_TABLE_INFORMATION_FAIL"

/* FILTER */
export const GET_ROADTANKER_FILTER = "ROADTANKER_FILTER"
export const GET_ROADTANKER_FILTER_SUCCESS = "GET_ROADTANKER_FILTER_SUCCESS"
export const GET_ROADTANKER_FILTER_FAIL = "GET_ROADTANKER_FILTER_FAIL"
