export const GET_PRODUCTS = "GET_PRODUCTS"
export const GET_PRODUCT_SUCCESS = "GET_PRODUCT_SUCCESS"
export const GET_PRODUCT_FAIL = "GET_PRODUCT_FAIL"

/* AUDIT LOG */
export const GET_PRODUCT_AUDITLOG = "PRODUCT_AUDITLOG"
export const GET_PRODUCT_AUDITLOG_SUCCESS = "GET_PRODUCT_AUDITLOG_SUCCESS"
export const GET_PRODUCT_AUDITLOG_FAIL = "GET_PRODUCT_AUDITLOG_FAIL"

export const GET_PRODUCT_FILTER = "PRODUCT_FILTER"
export const GET_PRODUCT_FILTER_SUCCESS = "GET_PRODUCT_FILTER_SUCCESS"
export const GET_PRODUCT_FILTER_FAIL = "GET_PRODUCT_FILTER_FAIL"

export const GET_PRODUCT_DETAIL = "GET_PRODUCT_DETAIL"
export const GET_PRODUCT_DETAIL_SUCCESS = "GET_PRODUCT_DETAIL_SUCCESS"
export const GET_PRODUCT_DETAIL_FAIL = "GET_PRODUCT_DETAIL_FAIL"


export const UPDATE_PRODUCT_DETAIL = "UPDATE_PRODUCT_DETAIL"
export const UPDATE_PRODUCT_DETAIL_SUCCESS = "UPDATE_PRODUCT_DETAIL_SUCCESS"
export const UPDATE_PRODUCT_DETAIL_FAIL = "UPDATE_PRODUCT_DETAIL_FAIL"