// Download
export const GET_DQM_EXCEL_DOWNLOAD = "GET_DQM_EXCEL_DOWNLOAD"
export const GET_DQM_EXCEL_DOWNLOAD_SUCCESS = "GET_DQM_EXCEL_DOWNLOAD_SUCCESS"
export const GET_DQM_EXCEL_DOWNLOAD_FAIL = "GET_DQM_EXCEL_DOWNLOAD_FAIL"
export const GET_DQM_EXCEL_DOWNLOAD_CLEAR = "GET_DQM_EXCEL_DOWNLOAD_CLEAR"

