export const GET_ORDERBANK = "GET_ORDERBANK"
export const GET_ORDERBANK_SUCCESS = "GET_ORDERBANK_SUCCESS"
export const GET_ORDERBANK_FAIL = "GET_ORDERBANK_FAIL"

/* TABLE INFORMATION */
export const GET_ORDERBANK_TABLE_INFORMATION = "GET_ORDERBANK_TABLE_INFORMATION"
export const GET_ORDERBANK_TABLE_INFORMATION_SUCCESS = "GET_ORDERBANK_TABLE_INFORMATION_SUCCESS"
export const GET_ORDERBANK_TABLE_INFORMATION_FAIL = "GET_ORDERBANK_TABLE_INFORMATION_FAIL"

export const UPDATE_ORDERBANK_TABLE_INFORMATION = "UPDATE_ORDERBANK_TABLE_INFORMATION"
export const UPDATE_ORDERBANK_TABLE_INFORMATION_SUCCESS = "UPDATE_ORDERBANK_TABLE_INFORMATION_SUCCESS"
export const UPDATE_ORDERBANK_TABLE_INFORMATION_FAIL = "UPDATE_ORDERBANK_TABLE_INFORMATION_FAIL"
