export const GET_RTS_ORDER_BANK_TABLE_DATA = "GET_RTS_ORDER_BANK_TABLE_DATA"
export const GET_RTS_ORDER_BANK_TABLE_DATA_SUCCESS = "GET_RTS_ORDER_BANK_TABLE_DATA_SUCCESS"
export const GET_RTS_ORDER_BANK_TABLE_DATA_FAIL = "GET_RTS_ORDER_BANK_TABLE_DATA_FAIL"

export const GET_SHIPMENT_ORDER_BANK_TABLE_DATA = "GET_SHIPMENT_ORDER_BANK_TABLE_DATA"
export const GET_SHIPMENT_ORDER_BANK_TABLE_DATA_SUCCESS = "GET_SHIPMENT_ORDER_BANK_TABLE_DATA_SUCCESS"
export const GET_SHIPMENT_ORDER_BANK_TABLE_DATA_FAIL = "GET_SHIPMENT_ORDER_BANK_TABLE_DATA_FAIL"

export const GET_ORDERBANK = "GET_ORDERBANK"
export const GET_ORDERBANK_SUCCESS = "GET_ORDERBANK_SUCCESS"
export const GET_ORDERBANK_FAIL = "GET_ORDERBANK_FAIL"

/* TABLE INFORMATION */
export const GET_ORDERBANK_TABLE_INFORMATION = "GET_ORDERBANK_TABLE_INFORMATION"
export const GET_ORDERBANK_TABLE_INFORMATION_SUCCESS = "GET_ORDERBANK_TABLE_INFORMATION_SUCCESS"
export const GET_ORDERBANK_TABLE_INFORMATION_FAIL = "GET_ORDERBANK_TABLE_INFORMATION_FAIL"

export const UPDATE_ORDERBANK_TABLE_INFORMATION = "UPDATE_ORDERBANK_TABLE_INFORMATION"
export const UPDATE_ORDERBANK_TABLE_INFORMATION_SUCCESS = "UPDATE_ORDERBANK_TABLE_INFORMATION_SUCCESS"
export const UPDATE_ORDERBANK_TABLE_INFORMATION_FAIL = "UPDATE_ORDERBANK_TABLE_INFORMATION_FAIL"

export const REFRESH_ORDER_BANK_DN = "REFRESH_ORDER_BANK_DN"
export const REFRESH_ORDER_BANK_DN_FAIL = "REFRESH_ORDER_BANK_DN_FAIL"
export const REFRESH_ORDER_BANK_SUCCESS = "REFRESH_ORDER_BANK_DN_SUCCESS"

export const SEND_ORDER_BANK_DN = "SEND_ORDER_BANK_DN"
export const SEND_ORDER_BANK_DN_SUCCESS = "SEND_ORDER_BANK_DN_SUCCESS"
export const SEND_ORDER_BANK_DN_FAIL = "SEND_ORDER_BANK_DN_FAIL"
export const UPDATE_ORDER_BANK_TABLE_DATA = "UPDATE_ORDER_BANK_TABLE_DATA"

export const DELETE_ORDERBANK_DETAIL = "DELETE_ORDERBANK_DETAIL"
export const DELETE_ORDERBANK_DETAIL_SUCCESS = "DELETE_ORDERBANK_DETAIL_SUCCESS"
export const DELETE_ORDERBANK_DETAIL_FAIL = "DELETE_ORDERBANK_DETAIL_FAIL"

export const SEND_DN_STATUS_REQUEST = "SEND_DN_STATUS_REQUEST"
export const SEND_DN_STATUS_REQUEST_SUCCESS = "SEND_DN_STATUS_REQUEST_SUCCESS"
export const SEND_DN_STATUS_REQUEST_FAIL = "SEND_DN_STATUS_REQUEST_FAIL"

export const GET_ORDER_BANK_AUDITLOG = "GET_ORDER_BANK_AUDITLOG"
export const GET_ORDER_BANK_AUDITLOG_SUCCESS = "GET_ORDER_BANK_AUDITLOG_SUCCESS"
export const GET_ORDER_BANK_AUDITLOG_FAIL = "GET_ORDER_BANK_AUDITLOG_FAIL"

// action for gantt chart
export const PROCESS_PAYMENT_IN_GANTT_CHART = "PROCESS_PAYMENT_IN_GANTT_CHART"
export const PROCESS_PAYMENT_IN_GANTT_CHART_SUCCESS = "PROCESS_PAYMENT_IN_GANTT_CHART_SUCCESS"
export const PROCESS_PAYMENT_IN_GANTT_CHART_FAIL = "PROCESS_PAYMENT_IN_GANTT_CHART_FAIL"


export const CANCEL_PAYMENT_IN_GANTT_CHART = "CANCEL_PAYMENT_IN_GANTT_CHART"
export const CANCEL_PAYMENT_IN_GANTT_CHART_SUCCESS = "CANCEL_PAYMENT_IN_GANTT_CHART_SUCCESS"
export const CANCEL_PAYMENT_IN_GANTT_CHART_FAIL = "CANCEL_PAYMENT_IN_GANTT_CHART_FAIL"

export const SEND_ORDER_IN_GANTT_CHART = "SEND_ORDER_IN_GANTT_CHART"
export const SEND_ORDER_IN_GANTT_CHART_SUCCESS = "SEND_ORDER_IN_GANTT_CHART_SUCCESS"
export const SEND_ORDER_IN_GANTT_CHART_FAIL = "SEND_ORDER_IN_GANTT_CHART_FAIL"

export const GET_RTS_GANTT_CHART_DATA = "GET_RTS_GANTT_CHART_DATA"
export const GET_RTS_GANTT_CHART_DATA_SUCCESS = "GET_RTS_GANTT_CHART_DATA_SUCCESS"
export const GET_RTS_GANTT_CHART_DATA_FAIL = "GET_RTS_GANTT_CHART_DATA_FAIL"

export const DRAG_RTS_ORDER_BANK_TO_GANTT_CHART = "DRAG_RTS_ORDER_BANK_TO_GANTT_CHART"
export const DRAG_RTS_ORDER_BANK_TO_GANTT_CHART_FAIL = "DRAG_RTS_ORDER_BANK_TO_GANTT_CHART_FAIL"
export const DRAG_RTS_ORDER_BANK_TO_GANTT_CHART_SUCCESS = "DRAG_RTS_ORDER_BANK_TO_GANTT_CHART_SUCCESS"

export const SELECT_VEHICLE_RTS_SHIPMENT = "SELECT_VEHICLE_RTS_SHIPMENT"
export const DESELECT_VEHICLE_RTS_SHIPMENT = "UNSELECT_VEHICLE_RTS_SHIPMENT"

export const REMOVE_ORDER_FROM_SHIPMENT = "REMOVE_ORDER_FROM_SHIPMENT"
export const REMOVE_ORDER_FROM_SHIPMENT_SUCCESS = "REMOVE_ORDER_FROM_SHIPMENT_SUCCESS"

export const REMOVE_SHIPMENT_FROM_EVENT = "REMOVE_SHIPMENT_FROM_EVENT"
export const REMOVE_SHIPMENT_FROM_EVENT_SUCCESS = "REMOVE_SHIPMENT_FROM_EVENT_SUCCESS"

export const REMOVE_EVENT = "REMOVE_EVENT"
export const REMOVE_EVENT_SUCCESS = "REMOVE_EVENT_SUCCESS"
export const REMOVE_EVENT_FAIL = "REMOVE_EVENT_FAIL"
