export const GET_SALES_AND_INVENTORY_VARIANCE_CONTROL =
  "GET_SALE_AND_INVENTORY_VARIANCE_CONTROL"
export const GET_SALES_AND_INVENTORY_VARIANCE_CONTROL_SUCCESS =
  "GET_SALE_AND_INVENTORY_VARIANCE_CONTROL_SUCCESS"
export const GET_SALES_AND_INVENTORY_VARIANCE_CONTROL_FAILED =
  "GET_SALE_AND_INVENTORY_VARIANCE_CONTROL_FAILED"
export const UPDATE_SALES_AND_INVENTORY_VARIANCE_CONTROL =
  "UPDATE_SALE_AND_INVENTORY_VARIANCE_CONTROL"
export const UPDATE_SALES_AND_INVENTORY_VARIANCE_CONTROL_SUCCESS =
  "UPDATE_SALE_AND_INVENTORY_VARIANCE_CONTROL_SUCCESS"
export const UPDATE_SALES_AND_INVENTORY_VARIANCE_CONTROL_FAILED =
  "UPDATE_SALE_AND_INVENTORY_VARIANCE_CONTROL_FAILED"
//tank status modal
export const GET_SALES_AND_INVENTORY_TANK_STATUS =
  "GET_SALES_AND_INVENTORY_TANK_STATUS"
export const GET_SALES_AND_INVENTORY_TANK_STATUS_SUCCESS =
  "GET_SALES_AND_INVENTORY_TANK_STATUS_SUCCESS"
export const GET_SALES_AND_INVENTORY_TANK_STATUS_FAILED =
  "GET_SALES_AND_INVENTORY_TANK_STATUS_FAILED"
export const UPDATE_SALES_AND_INVENTORY_TANK_STATUS =
  "UPDATE_SALES_AND_INVENTORY_TANK_STATUS"
export const UPDATE_SALES_AND_INVENTORY_TANK_STATUS_SUCCESS =
  "UPDATE_SALES_AND_INVENTORY_TANK_STATUS_SUCCESS"
export const UPDATE_SALES_AND_INVENTORY_TANK_STATUS_FAILED =
  "UPDATE_SALES_AND_INVENTORY_TANK_STATUS_FAILED"
// main table
export const GET_SALES_AND_INVENTORY = "GET_SALES_AND_INVENTORY"
export const GET_SALES_AND_INVENTORY_SUCCESS = "GET_SALES_AND_INVENTORY_SUCCESS"
export const GET_SALES_AND_INVENTORY_FAIL = "GET_SALES_AND_INVENTORY_FAIL"

/* main table filter */
export const GET_SALES_AND_INVENTORY_FILTER = "SALES_AND_INVENTORY_FILTER"
export const GET_SALES_AND_INVENTORY_FILTER_SUCCESS =
  "GET_SALES_AND_INVENTORY_FILTER_SUCCESS"
export const GET_SALES_AND_INVENTORY_FILTER_FAIL =
  "GET_SALES_AND_INVENTORY_FILTER_FAIL"
/* AUDIT LOG */
export const GET_SALES_AUDITLOG = "SALES_AUDITLOG"
export const GET_SALES_AUDITLOG_SUCCESS = "GET_SALES_AUDITLOG_SUCCESS"
export const GET_SALES_AUDITLOG_FAIL = "GET_SALES_AUDITLOG_FAIL"
/* DOWNLOAD */
export const GET_DOWNLOAD_SALES = "GET_DOWNLOAD_SALES"
export const GET_DOWNLOAD_SALES_SUCCESS = "GET_DOWNLOAD_SALES_SUCCESS"
export const GET_DOWNLOAD_SALES_FAIL = "GET_DOWNLOAD_SALES_FAIL"

/* DETAIL */
export const GET_DETAIL_SALES = "GET_DETAIL_SALES"
export const GET_DETAIL_SALES_SUCCESS = "GET_DETAIL_SALES_SUCCESS"
export const GET_DETAIL_SALES_FAIL = "GET_DETAIL_SALES_FAIL"

/* UPDATE SALES AND INVENTORY DETAIL */
export const UPDATE_SALES_AND_INVENTORY_DETAIL =
  "UPDATE_SALES_AND_INVENTORY_DETAIL"
export const UPDATE_SALES_AND_INVENTORY_DETAIL_SUCCESS =
  "UPDATE_SALES_AND_INVENTORY_DETAIL_SUCCESS"
export const UPDATE_SALES_AND_INVENTORY_DETAIL_FAIL =
  "UPDATE_SALES_AND_INVENTORY_DETAIL_FAIL"

export const OVERRIDE_STATUS_IN_ACTION_COLUMN =
  "OVERRIDE_STATUS_IN_ACTION_COLUMN"
