export const GET_RETAIL_CUSTOMER = "GET_RETAIL_CUSTOMER"
export const GET_RETAIL_CUSTOMER_SUCCESS = "GET_RETAIL_CUSTOMER_SUCCESS"
export const GET_RETAIL_CUSTOMER_FAIL = "GET_RETAIL_CUSTOMER_FAIL"

// Download
export const GET_DOWNLOAD_RETAIL_CUSTOMER = "GET_DOWNLOAD_RETAIL_CUSTOMER"
export const GET_DOWNLOAD_RETAIL_CUSTOMER_SUCCESS = "GET_DOWNLOAD_RETAIL_CUSTOMER_SUCCESS"
export const GET_DOWNLOAD_RETAIL_CUSTOMER_FAIL = "GET_DOWNLOAD_RETAIL_CUSTOMER_FAIL"

/* AUDIT LOG */
export const GET_RETAIL_AUDITLOG = "RETAIL_AUDITLOG"
export const GET_RETAIL_AUDITLOG_SUCCESS = "GET_RETAIL_AUDITLOG_SUCCESS"
export const GET_RETAIL_AUDITLOG_FAIL = "GET_RETAIL_AUDITLOG_FAIL"

/* TABLE INFORMATION */
export const GET_TABLE_INFORMATION = "GET_RETAIL_TABLE_INFORMATION"
export const GET_TABLE_INFORMATION_SUCCESS = "GET_RETAIL_TABLE_INFORMATION_SUCCESS"
export const GET_TABLE_INFORMATION_FAIL = "GET_RETAIL_TABLE_INFORMATION_FAIL"

export const UPDATE_TABLE_INFORMATION = "UPDATE_RETAIL_TABLE_INFORMATION"
export const UPDATE_TABLE_INFORMATION_SUCCESS =
  "UPDATE_RETAIL_TABLE_INFORMATION_SUCCESS"
export const UPDATE_TABLE_INFORMATION_FAIL = "UPDATE_RETAIL_TABLE_INFORMATION_FAIL"
export const RESET_RETAIL_TABLE_INFORMATION = "RESET_RETAIL_TABLE_INFORMATION"

/* FILTER */
export const GET_RETAIL_FILTER = "RETAIL_FILTER"
export const GET_RETAIL_FILTER_SUCCESS = "GET_RETAIL_FILTER_SUCCESS"
export const GET_RETAIL_FILTER_FAIL = "GET_RETAIL_FILTER_FAIL"

/* upload csv */
export const GET_UPLOAD_CSV = "GET_UPLOAD_CSV"
export const GET_UPLOAD_CSV_SUCCESS = "GET_UPLOAD_CSV_SUCCESS"
export const GET_UPLOAD_CSV_FAIL = "GET_UPLOAD_CSV_FAIL"

/* upload csv */
export const SET_UPLOAD_CSV = "SET_UPLOAD_CSV"
export const SET_UPLOAD_CSV_SUCCESS = "SET_UPLOAD_CSV_SUCCESS"

/* upload csv */
export const GET_DOWNLOAD_CSV = "GET_DOWNLOAD_CSV"
export const GET_DOWNLOAD_CSV_SUCCESS = "GET_DOWNLOAD_CSV_SUCCESS"
export const GET_DOWNLOAD_CSV_FAIL = "GET_DOWNLOAD_CSV_FAIL"
